# Data clearning & preparation for Orders dataset

In [1]:
import pandas as pd
import numpy as np

In [6]:
# import data 
df=pd.read_excel(r'E:\DATA Science\portfolio project\decodelab\ordersdatas.xlsx')
print("Shape of the dataset",df.shape)
print(df.head(5))

Shape of the dataset (1200, 14)
     OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0  ORD200000 2023-01-04     C72649  Monitor         5     570.62
1  ORD200001 2024-08-23     C75739    Phone         2     151.35
2  ORD200002 2024-02-27     C81728   Tablet         5     550.68
3  ORD200003 2023-10-15     C33540    Chair         1     273.19
4  ORD200004 2025-05-08     C81840  Printer         4     626.01

  ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0     928 Main St    Debit Card     Shipped    TRK37947903            7
1     823 Main St        Online     Shipped    TRK91186779            3
2     512 Main St   Credit Card   Cancelled    TRK42903982            8
3     275 Main St    Debit Card    Returned    TRK62788070            5
4     668 Main St        Online   Delivered    TRK29241424            8

  CouponCode ReferralSource  TotalPrice
0     SAVE10      Instagram     2853.10
1     SAVE10       Referral      302.70
2   FREESHIP          Email     2753.40
3     SAVE10       Facebook      273.19
4     SAVE10          Email     2504.04

In [7]:
# datatypes
df.dtypes

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [10]:
# checking null values
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [11]:
# filling CouponCode null values with "NO Coupan"
df['CouponCode']=df['CouponCode'].fillna('NO Coupan')

#Recheking missing values
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [13]:
# checking duplicates
df.duplicated().sum()

np.int64(0)

In [18]:
# Check unique values in text columns
print(df['OrderStatus'].unique())
print(df['PaymentMethod'].unique())
print(df['ReferralSource'].unique())
print(df['Product'].unique())

['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']
['Debit Card' 'Online' 'Credit Card' 'Gift Card' 'Cash']
['Instagram' 'Referral' 'Email' 'Facebook' 'Google']
['Monitor' 'Phone' 'Tablet' 'Chair' 'Printer' 'Laptop' 'Desk']

In [20]:
# checking outliers in Quantity, UnitPrice, and TotalPrice

df[['Quantity', 'UnitPrice', 'TotalPrice']].describe()

          Quantity    UnitPrice   TotalPrice
count  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750  1053.968300
std       1.407557   197.177146   819.856558
min       1.000000    11.390000    11.390000
25%       2.000000   186.062500   410.520000
50%       3.000000   364.210000   823.615000
75%       4.000000   521.570000  1578.475000
max       5.000000   699.930000  3456.400000

In [21]:
# validating TotalPrice matches Quantity × UnitPrice

df['calculated'] = df['Quantity'] * df['UnitPrice']
mismatch = df[df['calculated'].round(2) != df['TotalPrice'].round(2)]
print(mismatch[['OrderID','Quantity','UnitPrice','TotalPrice','calculated']])

Empty DataFrame
Columns: [OrderID, Quantity, UnitPrice, TotalPrice, calculated]
Index: []

In [22]:
# remove calculated column
df.drop(columns=['calculated'], inplace=True)

In [48]:
# Extract date features from Date column

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.day_name()
df['WeekNum'] = df['Date'].dt.isocalendar().week

In [32]:
# Create a Revenue bin / category for TotalPrice

df['PriceCategory'] = pd.cut(df['TotalPrice'], 
                              bins=[0, 500, 1500, 3500],
                              labels=['Low', 'Medium', 'High'])

In [33]:
print("Total Revenue:", df['TotalPrice'].sum())
print("Total Orders:", df['OrderID'].nunique())
print("Average Order Value:", df['TotalPrice'].mean())
print("Most Sold Product:", df['Product'].value_counts().idxmax())

Total Revenue: 1264761.96
Total Orders: 1200
Average Order Value: 1053.9683
Most Sold Product: Printer

In [50]:
print(df.shape)
print(df.info())

(1200, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
 14  Year             1200 non-null   int32
 15  Month            1200 non-null   int32
 16  Day              1200 non-null   int32
 17  DayOfWeek        1200 non-null   object
 18  PriceCategory    1200 non-null   category
 19  WeekNum          1200 non-null   UInt32
dtypes: UInt32(1), category(1), datetime64[ns](1), float64(2), int32(3), int64(2), object(10)
memory usage: 162.0+ KB
None

In [52]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day,DayOfWeek,PriceCategory,WeekNum
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1,4,Wednesday,High,1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8,23,Friday,Low,34
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2,27,Tuesday,High,9
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10,15,Sunday,Low,41
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5,8,Thursday,High,19

In [57]:
#saving clean data

df.to_excel("CleanOrdersData.xlsx", index=False)

In [37]:
print("-"*40)
print(" Data Cleaning & Preparation Done")
print("-"*40)

----------------------------------------
 Data Cleaning & Preparation Done
----------------------------------------